version: "3.9"

services:
  nginx:
    container_name: nginx
    build: docker/nginx
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./bardo:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - "8080:80"

  app:
    container_name: app
    build: docker/app
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./bardo:/app

  mysql:
    container_name: mysql
    build: docker/mysql
    tty: true

    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./docker/mysql/initdb.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MYSQL_DATABASE=bardo
      - MYSQL_ROOT_PASSWORD=root

networks:
  default:
    driver: bridge